CREATE SEQUENCE sessao_id_seq;

CREATE TABLE sessao (
    id INTEGER DEFAULT NEXTVAL('sessao_id_seq') NOT NULL,
    id_pauta INTEGER UNIQUE NOT NULL REFERENCES pauta(id),
    contabilizada BOOLEAN NOT NULL DEFAULT false,
	data_abertura TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	data_encerramento TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 minute',
    PRIMARY KEY (id)
);